config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  devise_for :admins
  
  authenticate :admin do 
    resources :products
    resources :categories
  end 
  
  resource :cart, only: [:show, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  ORDER_PREFIX = 'PO'
  RANDOM_SIZE = 9
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items 
  before_create -> { generate_number (RANDOM_SIZE) }

  validates :number, uniqueness: true

  def add_product(product_id, quantity)
    product = Product.find(product_id)
      if product && product.stock > 0
        order_items.create(product_id: product.id, quantity: quantity, price: product.price)
        the_total
      end
  end

  def generate_number(size)
    self.number = loop do
      rand_str = random_candidate(size)
      break rand_str unless Order.exists?(number: rand_str)
    end
  end

  def random_candidate(size)
    "#{ORDER_PREFIX}#{Array.new(size){rand(size)}.split}"
  end

  def the_total
    sum = 0
    order_items.each do |item|
      sum += item.price
    end
    update_attribute(:total,sum)
  end

    def in_cents
      self.total *100
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    has_and_belongs_to_many :categories
    has_many :order_items
    has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_order
        if current_user
            order = Order.find_or_create_by(user_id: current_user.id, state: 'created')
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!
    def update
        product = params[:cart][:product_id]
        quantity = params[:cart][:quantity]
        
        current_order.add_product(product, quantity)
        
        redirect_to root_url, notice: "Product added successfuly"
    end
    
    def show
        @order = current_order
    end
        
    def pay_with_paypal
        order = Order.find(params[:cart][:order_id])
        
        #price must be in cents
        price = order.in_cents
        response = define_response(price)
        payment_method = PaymentMethod.find_by(code: "PEC")
        Payment.create_order(order, payment_method, response)
        redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
    end
        
    def process_paypal_payment
        details = EXPRESS_GATEWAY.details_for(params[:token])
        express_purchase_options(request, params[:token], details)
        price = details.params["order_total"]to_decimal_per100(price)
        
        response = EXPRESS_GATEWAY.purchase(price, express_purchase_options)
        successfuly_response(response)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :stock, :price, :sku, {category_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<​div​ class="card">
    <div​ class= "card-header bg-dark text-light"​>
        <​i class=​ "fa fa-shopping-cart"​ aria-hidden=​ "true"​ ></​i>
        <​a href=​"<%=​ root_url​%>"​ class=​ "btn btn-outline-info btn-sm pull-right"​ >Continue Shopping</​a>
        <div​ class=​ "clearfix"​ ></​ div​ >
    </​div​ >    
    <​div​ class=​ "card-body"​ >
        <​% ​ @order.order_items.includes(​:product​).each ​ do​ |item| %>
            <div​ class=​ "row"​ >
                <​div​ class=​ "col-xs-2 col-md-2"​>
                    <img​ class=​ "img-responsive" src=​ "http://placehold.it/120x80"​ alt=​ "prewiew"​ >
                </div​>

                <​div​ class=​ "col-xs-4 col-md-6"​ >
                    <h4​ class=​ "product-name"​ ><​ strong​ ><​%=​ item.product.name%></​ strong​ ></​h4​><h4​><​small><​%=​ item.product.description %></​small></h4 >
                </​div​>

                <​div​ class=​ "col-xs-6 col-md-4 row"​ >
                    <div​ class=​ "col-xs-6 col-md-6 text-right" style=​ "padding-top: 5px"​ ><​h6​><​strong><%=​ item.price%><​span class=​ "text-muted"​ >x</​span></strong></h6>
                    </div >

                    <div​ class=​ "col-xs-4 col-md-4">
                        <%=​ item.quantity %>
                    </​div>

                    <​div​ class=​ "col-xs-2 col-md-2"​>
                    </​div​ >
                </​ div​ >
            </​ div​ >
            <​hr>
        <​%end​ %>
    </​div>
    <​div​ class=​"card-footer"​>
        <a href=​ "#"​ class=​ "btn btn-success pull-right"​ >Pay</​a>
        <​div​ class=​ "pull-right"​ style=​ "margin: 5px"​>
            Total: $<​ b ​ ><​ %=​ @order.total %></​ b ​ >
        </div>
    </​div​ >
</​ div​ >

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h2 class='text-center'>Productos</h2>
<% @products.each_slice(4) do |products| %>
    <div class="card-deck">
        <% products.each do |product| %>
            <div class='card'>
                <%= image_tag 'https://dummyimage.com/600x400/c7c7c7/737373&text=image', class:'card-img-top img-fluid' %>
                    <div class='card-body'>
                        <h5 class='card-title'><%= product.name %></h5>
                        <div class='card-text'>
                            <div class='badge badge-primary'><%= product.categories.name %></div>
                                <div>
                                    <%= number_to_currency product.price %>
                                </div>
                                <%= form_for :cart, url: cart_path, method: :put do |f| %>
                                    <%= f.hidden_field :product_id, value: product.id %>
                                    <%= f.hidden_field :quantity, value: 1 %>
                                    <%= f.submit "Add to cart", class:'btn btn-primary btn-sm float-right' %>
                                <% end %>
                                </div>
                            </div>        
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <title>EcommerceRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>
  
  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
        <% b.label class:"label-checkbox" do %>
          <% b.check_box + b.text %>
          <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Price</th>
      <th>Sku</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td><%= product.price %></td>
        <td><%= product.sku %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>